
#pragma once

#define VERSION_MAJOR (${VERSION_MAJOR})
#define VERSION_MINOR (${VERSION_MINOR})
#define VERSION_PATCH (${VERSION_PATCH})
#define VERSION_GIT_BRANCH "${VERSION_GIT_BRANCH}"
#define VERSION_GIT_HASH "${VERSION_GIT_HASH}"
#cmakedefine RELEASE_BUILD