name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build-win64:
    runs-on: [self-hosted, windows, X64]
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: |
          cmake -B build -G Ninja "-DSDL3_DIR=C:\Libraries\SDL3-3.4.8\cmake" "-DQt6_DIR=C:\Libraries\Qt-6.11.0\lib\cmake\Qt6" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j $([Environment]::ProcessorCount)
      - name: Collect artifacts
        run: |
          New-Item -ItemType Directory upload
          Copy-Item -Recurse build\bin\qt\Release\platforms,build\bin\qt\Release\styles,build\bin\qt\Release\NanoBoyAdvance.exe,build\bin\qt\Release\Qt6Core.dll,build\bin\qt\Release\Qt6Gui.dll,build\bin\qt\Release\Qt6Widgets.dll,C:\Libraries\SDL3-3.4.8\lib\SDL3.dll -Destination upload
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: NanoBoyAdvance-${{ runner.os }}-${{ runner.arch }}
          path: upload
          if-no-files-found: error

  build-linux:
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DPORTABLE_MODE=OFF
          cmake --build build -j$(nproc)
      - name: Create AppDir
        run: | # Yes, this is done by hand. fight me
          mkdir -p AppDir/usr/bin AppDir/usr/share/applications AppDir/usr/share/icons/hicolor/128x128/apps
          cp -r build/bin/qt/Release/NanoBoyAdvance AppDir/usr/bin/
          cp -r src/platform/qt/resources/Linux/io.nanoboyadvance.NanoBoyAdvance.desktop AppDir/usr/share/applications/
          cp -r src/platform/qt/resources/Linux/io.nanoboyadvance.NanoBoyAdvance.png AppDir/usr/share/icons/hicolor/128x128/apps/
      - name: Build AppImage
        env:
          EXTRA_PLATFORM_PLUGINS: libqwayland-egl.so;libqwayland-generic.so
          EXTRA_QT_PLUGINS: core;dbus;gui;waylandcompositor;widgets
          QMAKE: /usr/lib/qt6/bin/qmake
        run: /usr/local/bin/linuxdeploy --appdir AppDir --plugin qt --output appimage
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: NanoBoyAdvance-${{ runner.os }}-${{ runner.arch }}
          path: NanoBoyAdvance*.AppImage
          if-no-files-found: error

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup dependencies
        env:
          HOMEBREW_NO_ANALYTICS: 1
        run: |
          brew install qt@6 sdl3
      - name: Build
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DMACOS_BUILD_APP_BUNDLE=ON
          cmake --build build -j$(sysctl -n hw.logicalcpu)
      - name: Create disk image
        run: |
          mkdir dmg
          cp -a build/bin/qt/Release/NanoBoyAdvance.app dmg/NanoBoyAdvance.app
          codesign -s - --deep -f dmg/NanoBoyAdvance.app
          ln -s /Applications dmg/Applications
          hdiutil create -fs HFS+ -volname NanoBoyAdvance -srcfolder dmg -ov -format UDBZ NanoBoyAdvance-arm64.dmg
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: NanoBoyAdvance-${{ runner.os }}-${{ runner.arch }}
          path: NanoBoyAdvance-arm64.dmg
          archive: false
          if-no-files-found: error
